# Generated by Django 3.2.13 on 2022-07-03 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='recette_name', max_length=100)),
                ('image', models.ImageField(upload_to='recette_img')),
                ('describe', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ingredient name', max_length=100)),
                ('quantity', models.CharField(default='10', max_length=20)),
                ('unite', models.CharField(default='g', max_length=20)),
                ('recette', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='blog.recette')),
            ],
        ),
    ]
