# Generated by Django 3.2.13 on 2022-07-04 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='parent',
        ),
    ]
