# Generated by Django 3.2.13 on 2022-07-04 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_categorie_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='categori',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.categorie'),
            preserve_default=False,
        ),
    ]
