# Generated by Django 3.2.13 on 2022-07-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_recette_categori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
