# Generated by Django 3.2.13 on 2022-07-04 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_recette_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100)),
                ('pseudo', models.CharField(default='name', max_length=100)),
                ('mdp', models.CharField(default='name', max_length=100)),
                ('email', models.CharField(default='name', max_length=100)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recette',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='blog.recette'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='categori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.categorie'),
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(default='autor name', max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('note', models.IntegerField()),
                ('date_post', models.DateTimeField(auto_now_add=True)),
                ('crecette', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='blog.recette')),
            ],
        ),
        migrations.AddField(
            model_name='recette',
            name='membre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membre', to='blog.membre'),
        ),
    ]
